[model] add control.py
wuhanstudio/adversarial-ros-detection pull request #1
Opened 2021-06-22 15:49 UTC by suyunas

2021-06-22 16:02 UTC, wuhanstudio requested changes

2021-06-22 16:02 UTC, wuhanstudio commented on model/control.py
> +hello first atte3mpt
pls add a python file

2021-06-22 16:02 UTC, suyunas commented on model/control.py
> +hello first atte3mpt
file added but need some code

2021-06-22 16:05 UTC, wuhanstudio commented on model/control.py
> +hello first atte3mpt
Subscribe to /detect topic:

- 0: nothing detected
- 1: 30   --> linear.x = 0.01
- 2: stop  --> linear.x = 0
- 3: 60  --> linear.x =0.02

2021-06-23 16:37 UTC, suyunas commented on model/control.py
> +hello first atte3mpt
Having some problems with type of '/detect' as String. However changing it to Int32 works. Kindly check

2021-06-23 16:50 UTC, wuhanstudio commented on model/control.py
> +pub = rospy.Publisher('/cmd_vel', Twist)
Thank you, ROS decouples each component, making the control logic pretty clear.

But suddenly I realize that this may conflict with line tracking, which publishes /cmd_vel as well. 

Perhaps we can publish /cmd_vel_steer in line tracking. Then this control node subscribes and takes angular.z from /cmd_vel_steer, and publishes the final /cmd_vel. What do you think?

2021-06-28 13:32 UTC, merged